### ISSUE TITLE
White spaces handling PrometheusRules CR 

### ISSUE THREAD

**Issue by kamolhasan** [appscode/alerts#5]
```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
spec:
  groups:
  {{ if  gruop -}}
  - name: elasticsearch.database.{{- .Values.namespace -}}.{{- .Values.dbName }}.rules
    rules:
    {{ if .Values.alert.groups.database.rules.elasticsearchHeapUsageTooHigh.enabled -}}
    - ... ...
    {{ end -}}
    ... ...
    {{ if .Values.alert.groups.database.rules.elasticsearchHeapUsageTooHigh.enabled -}}
    - ... ...
    {{- end }} # only exception here, the last alert before group ends. 
  {{ end -}}
  
  {{ if .Values.alert.groups.kubedb.enabled -}}
  - ... ... 
  {{ end -}}    
  
  ```
  
  **Goal:** No more than one empty line in between alerts/groups
